// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnEEdu0pqeeIm3Too_9JobDYeH-wAmxrQ',
    appId: '1:1001685338819:web:d43a357d3d5f7f71277076',
    messagingSenderId: '1001685338819',
    projectId: 'ndri-risk-app',
    authDomain: 'ndri-risk-app.firebaseapp.com',
    storageBucket: 'ndri-risk-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAas6vkcxJDVpWt3XBLY4Xaa3KJDFHRsgk',
    appId: '1:1001685338819:android:e24df40885ceb1d1277076',
    messagingSenderId: '1001685338819',
    projectId: 'ndri-risk-app',
    storageBucket: 'ndri-risk-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhuwnd3BmUNLVbPOaXJ8Uy3c3YyF4Qtno',
    appId: '1:1001685338819:ios:25b610ea596d3575277076',
    messagingSenderId: '1001685338819',
    projectId: 'ndri-risk-app',
    storageBucket: 'ndri-risk-app.firebasestorage.app',
    iosBundleId: 'com.example.ndriDairyRisk',
  );
}
